
export const AGENTS: Record<string, string> = {
    "190357": "Ali Y.", "189684": "Ferhat S.", "221239": "Tuncay A.", "216588": "Christopher R.", "217197": "AliCem Y.",
    "215988": "Metin S.", "215989": "Helmut W.", "197910": "Joachim L.", "214432": "Yasin U.", "201747": "Deniz T.",
    "216043": "Dikmen Y.", "196739": "Mehmet O.", "191247": "Umut C.", "209089": "Emre K.", "209095": "YasinIhsan O.",
    "190338": "MuhammedTuran A.", "190340": "Erkan K.", "191248": "Yeliz O.", "192228": "Guelseren D.", "192235": "Zuelkif D.",
    "192240": "Baseliyas D.", "192241": "Johann S.", "192243": "Oerer U.", "191207": "Halife A.", "207468": "Ufuk B.",
    "207470": "Muhammed C.", "207478": "Cueneyt K.", "207480": "Deniz K.", "194751": "Mustafa B.", "194754": "Esra C.",
    "191208": "Mahmut A.", "165145": "Osman K.", "213860": "Anne S.", "213863": "MehmetAli N.", "213864": "Sergen B.",
    "210949": "Yadin B.", "165604": "Leyla U.", "212854": "Deniz B.", "212855": "Yadiger D.", "212859": "Kirsten S.",
    "219925": "Baris d.", "219930": "Heiko S.", "219931": "Lydia S.", "218421": "Betuel C.", "218422": "Emre C.",
    "215987": "DursunAli O.", "199362": "Saban A.", "214007": "Tuba O.", "201743": "Amira A.", "201748": "Nevzat T.",
    "201750": "Vedat Y.", "216041": "Akhan S.", "216042": "Mithat S.", "196849": "Yueksel B.", "202266": "Dilara K.",
    "202268": "Zafer S.", "191592": "Abdullah S.", "192246": "Aysun U.", "203949": "Semra D.", "203959": "Oktay I.",
    "210681": "Volkan D.", "210695": "Cigdem I.", "207469": "Muecahit B.", "207474": "MelanieSusan F.", "207477": "Eymen K.",
    "207483": "Meric U.", "206033": "Sueleyman A.", "194753": "Yeliz C.", "194755": "Meryem C.", "205610": "Imdat H.",
    "173747": "Bekir E.", "193167": "Ozan Y.", "204223": "Tayfun K.", "204224": "Habib A.", "219922": "Tuba A.",
    "219924": "Goenuel D.", "219928": "Hacer K.", "219934": "Meryem V.", "218423": "Olga D.", "217195": "MuhammedBaki C.",
    "220243": "Miriam K.", "168014": "Abdullah G.", "218622": "Tugay E.", "181833": "Sedat Y.", "213967": "Dogan B.",
    "214006": "Orhan G.", "201744": "Isa E.", "201746": "Emir K.", "216035": "Ilhan A.", "216036": "Aykut C.",
    "202269": "Asli T.", "192227": "Kadir P.", "192231": "Ali K.", "203935": "Enis E.", "203952": "Guelahmet E.",
    "203962": "Hakki K.", "210678": "Oemer A.", "210685": "Sevcan I.", "210686": "Tuelay K.", "210687": "Buenyamin O.",
    "210696": "Abdullah K.", "210697": "Murat O.", "190693": "Kenan G.", "174351": "Emre T.", "204427": "Ali B.",
    "207473": "Filiz E.", "207476": "Erguen K.", "205611": "CahitSitki K.", "204222": "Hava K.", "212856": "Tezcan F.",
    "212858": "Methap S.", "218729": "Judith J.", "219923": "Alyona C.", "219932": "Patrick d.", "223947": "DilaraSelvi Y.",
    "215985": "Burak C.", "201749": "Sibel U.", "216033": "Yasin A.", "216039": "Tolga O.", "202272": "Volkan Y.",
    "209092": "Christian K.", "209093": "Goekce K.", "199408": "Mehmet E.", "199410": "Tanja K.", "199411": "Dilara-Selvi Y.",
    "210691": "Suendues A.", "207471": "Nedim D.", "207484": "Mustafa Z.", "213865": "Tugbahan E.", "218728": "Elena C.",
    "219926": "Heike E.", "219927": "Muzaffer E.", "219929": "Batuhan S.", "219933": "AliOender V.", "221240": "Felix A.",
    "221241": "Tugce S.", "221242": "Rami T.", "217196": "Natalie E.", "221243": "Burak U.", "221244": "ElenaAnastasia Y.",
    "221475": "Mustafa A.", "221731": "Zahra V.", "217607": "Funda B.", "217608": "Suat d.", "216034": "Mustafa A.",
    "220653": "Akin A.", "224368": "AlHilu A.", "224369": "Cemal C.", "224370": "Ibrahim C.", "224373": "Hakan G.",
    "224375": "Ozer O.", "224376": "Mahmut S.", "224589": "Dejan C.", "224229": "AbdelLatif A.", "224230": "Geng G.",
    "224233": "Cetin I.", "224234": "Sarikan M.", "224235": "Oztekin O.", "217286": "Aycan C.", "169146": "Aylin B.",
    "185217": "Dilek K.", "185221": "Yasar K.", "180589": "Britta U.", "215393": "Esra K.", "197909": "Saitoglu H.",
    "170990": "Bora C.", "220754": "Tuelay S.", "168784": "Selcuk G.", "180515": "Seyma B.", "173064": "Guel E.",
    "173068": "Sinem O.", "169945": "Rasim T.", "213968": "Tamer O.", "216419": "Jessica B.", "172508": "Canan O.",
    "199527": "Sercan G.", "202271": "Veysel Y.", "209096": "Akguen S.", "193216": "Caglar G.", "165511": "Guelcan U.",
    "190336": "AliEsref A.", "171564": "Ersin A.", "199409": "Anjelik K.", "220659": "Eda B.", "188292": "Ekatarina L.",
    "202087": "Dorin M.", "213668": "Ahmet A.", "164925": "Serhad K.", "206030": "Sibel N.", "163766": "Gursel G.",
    "163777": "Okan D.", "174916": "Fatih O.", "210961": "Tugce S.", "167168": "Nurcin A.", "224227": "Elina A.H.",
    "225131": "Pascal K.", "225128": "Emre G.", "225140": "Dalhanur A.", "225129": "Nicole R.", "225137": "Orhun K.",
    "225143": "Lydmilla F."
};

export interface ProvisionEntry {
  prod: string;
  code: string;
  value: number;
  class: string;
}

export const PROVISIONS: ProvisionEntry[] = [
  // ==========================================
  // TV SEGMENT (VKD_PTV_BNT) - Basic, GigaTV, Home, International
  // ==========================================
  { prod: "Vodafone Basic TV Cable", code: "HDC:399", value: 6.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone Basic TV Cable MVLZ 24M", code: "HDC:3BK", value: 6.00, class: "VKD_PTV_BNT" },
  { prod: "CI+ Modul Smart Miete", code: "CIS:na", value: 2.50, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Cable inkl. Netflix Tarifwechsel", code: "GNX:TW1", value: 20.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone Giga TV Cable inklusive HD Premium Cable", code: "UP2:na", value: 20.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Cable Premium (Box 2) Tarifwechsel", code: "UP3:TW2", value: 20.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Cable (Box 2) inkl. Netflix Tarifwechsel", code: "UPN:TW1", value: 20.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Mobile-App 1M frei", code: "AGT:001", value: 0.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Mobile App Flex", code: "AGT:TW1", value: 0.00, class: "VKD_PTV_BNT" },
  
  // GigaTV Home Promo
  { prod: "GigaTV Home Cable Promo", code: "GTH:006", value: 18.75, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable inkl. Netflix Promo", code: "GPN:006", value: 22.50, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable inkl. Premium Promo", code: "GPH:006", value: 21.25, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable 12M", code: "GTH:12M", value: 18.75, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable Multiroom Box 1", code: "MRI:na", value: 6.25, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable Multiroom Box 2", code: "MRK:na", value: 6.25, class: "VKD_PTV_BNT" },
  
  // GigaTV Home Sound Promo
  { prod: "GigaTV Home Sound Cable Promo", code: "GSH:006", value: 20.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable inkl. Netflix Promo", code: "GSN:006", value: 22.50, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable inkl. Premium Promo", code: "GSP:006", value: 23.75, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable Multiroom Box 1", code: "MRJ:na", value: 6.25, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable Multiroom Box 2", code: "MRL:na", value: 6.25, class: "VKD_PTV_BNT" },

  // GigaTV Home Tarifwechsel
  { prod: "GigaTV Home Cable Tarifwechsel", code: "GTH:TW1", value: 19.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable inkl. Netflix Tarifwechsel", code: "GPN:TW1", value: 19.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable inkl. Premium Tarifwechsel", code: "GPH:TW1", value: 19.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable Tarifwechsel", code: "GSH:TW1", value: 19.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable inkl. Netflix Tarifwechsel", code: "GSN:TW1", value: 19.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable inkl. Premium Tarifwechsel", code: "GSP:TW1", value: 19.00, class: "VKD_PTV_BNT" },

  // GigaTV Home Net (OTT)
  { prod: "GigaTV Home Net Promo", code: "GTV:006", value: 18.75, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Net inkl. Netflix Promo", code: "GTN:006", value: 22.50, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Net inkl. Premium Promo", code: "GTP:006", value: 21.25, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Net 12M", code: "GTV:TKG", value: 18.75, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Net Multiroom 1", code: "MRE:na", value: 6.25, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Net Multiroom 2", code: "MRF:na", value: 6.25, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Net Promo", code: "GTS:006", value: 20.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Net inkl. Netflix Promo", code: "GTF:006", value: 22.50, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Net inkl. Premium Promo", code: "GTR:006", value: 23.75, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Net Multiroom 1", code: "MRG:na", value: 6.25, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Net Multiroom 2", code: "MRH:na", value: 6.25, class: "VKD_PTV_BNT" },
  
  // GigaTV Home Net Tarifwechsel
  { prod: "GigaTV Home Net Tarifwechsel", code: "GTV:TW1", value: 19.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Net inkl. Netflix Tarifwechsel", code: "GTN:TW1", value: 19.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Net inkl. Premium Tarifwechsel", code: "GTP:TW1", value: 19.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Net Tarifwechsel", code: "GTS:TW1", value: 19.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Net inkl. Netflix Tarifwechsel", code: "GTF:TW1", value: 19.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Net inkl. Premium Tarifwechsel", code: "GTR:TW1", value: 19.00, class: "VKD_PTV_BNT" },

  // Premium / HD Optionen
  { prod: "Vodafone Premium Cable", code: "DV2:12M", value: 10.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone HD Premium Cable Partnerkarte", code: "DV2:2SC", value: 10.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone HD Premium Plus Cable", code: "DPP:na", value: 3.60, class: "VKD_PTV_BNT" },
  { prod: "Vodafone Premium Plus Erweiterung zu Premium Cable 2FM", code: "DPP:002", value: 3.60, class: "VKD_PTV_BNT" },
  { prod: "Vodafone Premium Plus Erweiterung zu Premium Cable 1M", code: "DPP:L01", value: 3.60, class: "VKD_PTV_BNT" },
  { prod: "HD Premium", code: "DV2:000", value: 10.00, class: "VKD_PTV_BNT" },
  { prod: "HD Premium T02", code: "DV2:T02", value: 10.00, class: "VKD_PTV_BNT" },
  { prod: "HD Premium Bonus", code: "DV2:BON", value: 10.00, class: "VKD_PTV_BNT" },
  { prod: "App HD Premium", code: "ACP:B00", value: 10.00, class: "VKD_PTV_BNT" },
  { prod: "App HD Premium 002", code: "ACP:002", value: 10.00, class: "VKD_PTV_BNT" },
  { prod: "HD Premium 2M NO Net/App", code: "ACP:T02", value: 0.00, class: "VKD_PTV_BNT" },
  { prod: "App Premium Plus", code: "ACE:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Premium Plus", code: "ACE:002", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "VTV3 OTT Erweiterung", code: "BS4:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "VSB OTT Erweiterung", code: "BS5:na", value: 0.00, class: "VKD_PTV_BNT" },
  { prod: "Netflix Bundle", code: "NFX:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Netflix Bundle OTT", code: "NFO:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Cable Multiroom Box 1", code: "MR3:na", value: 9.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Cable Multiroom Box 2", code: "MR4:na", value: 9.00, class: "VKD_PTV_BNT" },
  { prod: "Provisionsgoodie non-Cable footprint", code: "NCF:na", value: 0.00, class: "VKD_PTV_BNT" },

  // International Cable 2021
  { prod: "Vodafone TV International Cable - Albanisch", code: "IAL:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Arabisch", code: "IAR:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Bosnisch", code: "IBO:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Englisch", code: "IEN:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Französisch", code: "IFR:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Griechisch", code: "IGR:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Italienisch", code: "IIT:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Kroatisch", code: "IKR:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Polnisch", code: "IPL:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Portugiesisch", code: "IPG:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Russisch", code: "IRU:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Serbisch", code: "ISE:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Serbisch PINK", code: "IPI:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Spanisch", code: "ISP:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Türkisch Basis", code: "ITB:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV International Cable - Türkisch Premium", code: "ITP:na", value: 5.00, class: "VKD_PTV_BNT" },

  // International Gen3 (Net/App)
  { prod: "TV International Gen3 - Türkisch Premium", code: "1TP:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Türkisch Basis", code: "1TB:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Russisch", code: "1RU:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Italienisch", code: "1IT:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Spanisch", code: "1SP:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Pink", code: "1PI:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Serbisch", code: "1SE:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Kroatisch", code: "1KR:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Griechisch", code: "1GR:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Bosnisch", code: "1BO:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Albanisch", code: "1AL:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Englisch", code: "1EN:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Arabisch", code: "1AR:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Französisch", code: "1FR:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Polnisch", code: "1PL:na", value: 5.00, class: "VKD_PTV_BNT" },
  { prod: "TV International Gen3 - Portugiesisch", code: "1PG:na", value: 5.00, class: "VKD_PTV_BNT" },
  
  // App Addons
  { prod: "TV-International Englisch (GigaTV-App)", code: "AI1:na", value: 1.98, class: "VKD_PTV_BNT" },
  { prod: "TV-International Türkisch (GigaTV-App)", code: "AI2:na", value: 1.98, class: "VKD_PTV_BNT" },
  { prod: "TV-International Russisch (GigaTV-App)", code: "AI3:na", value: 1.98, class: "VKD_PTV_BNT" },
  { prod: "TV-International Italienisch (GigaTV-App)", code: "AI5:na", value: 1.98, class: "VKD_PTV_BNT" },

  // Prevention & Winback (TV)
  { prod: "GigaTV Home Cable Prevention", code: "GTH:PTV", value: 7.50, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable inkl. Netflix Prevention", code: "GPN:PTV", value: 7.50, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable inkl. Premium Prevention", code: "GPH:PTV", value: 8.75, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable Prevention", code: "GSH:PTV", value: 10.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable inkl. Netflix Prevention", code: "GSN:PTV", value: 10.00, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable inkl. Premium Prevention", code: "GSP:PTV", value: 11.25, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV Connect Start VV Sonderpreis Winback", code: "KSW:na", value: 0.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV Connect Start VV Coop Winback", code: "KVC:WTV", value: 2.50, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV Connect Start VV Markt Winback", code: "KV9:WTV", value: 2.50, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV Connect Standard Winback", code: "TCM:WTV", value: 3.75, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable Winback", code: "GTH:WTV", value: 17.60, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable inkl. Netflix Winback", code: "GPN:WTV", value: 17.60, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Cable inkl. Premium Winback", code: "GPH:WTV", value: 19.20, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable Winback", code: "GSH:WTV", value: 19.20, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable inkl. Netflix Winback", code: "GSN:WTV", value: 17.60, class: "VKD_PTV_BNT" },
  { prod: "GigaTV Home Sound Cable inkl. Premium Winback", code: "GSP:WTV", value: 19.20, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV Connect Tarifwechsel", code: "TC2:TW1", value: 10.80, class: "VKD_PTV_BNT" },
  { prod: "Vodafone Basic TV Cable Winback", code: "HDC:WTV", value: 6.40, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Cable Winback", code: "GT1:WTV", value: 12.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Cable inkl. Premium Cable Winback", code: "UP2:WTV", value: 13.50, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Cable inkl. Netflix Winback", code: "GNX:WTV", value: 22.50, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Cable (Box 2) inkl. Netflix Winback", code: "UPN:WTV", value: 22.50, class: "VKD_PTV_BNT" },
  { prod: "Vodafone TV Connect Winback 12M", code: "TC2:12W", value: 10.80, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Cable (Box 1) Winback 12M", code: "GT1:12W", value: 8.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Cable (Box 2) Winback", code: "GT3:WTV", value: 10.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Cable (Box 2) Winback 12M", code: "GT3:12W", value: 8.00, class: "VKD_PTV_BNT" },
  { prod: "Vodafone GigaTV Cable Premium (Box 2) Winback", code: "UP3:WTV", value: 22.50, class: "VKD_PTV_BNT" },

  // ==========================================
  // INTERNET / KIP - VVL / UPSELL
  // ==========================================
  { prod: "GigaZuhause BV 50/25 Kabel Upsell Standard", code: "5BV:na", value: 7.50, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 100/50 Kabel Upsell Standard", code: "4BV:na", value: 8.75, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 250/50 Kabel Upsell Standard", code: "3BV:na", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 500/50 Kabel Upsell Standard", code: "2BV:na", value: 12.50, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 1000/50 Kabel Upsell Standard", code: "1BV:na", value: 15.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 50/25 Kabel Standardangebot 12M", code: "6BV:na", value: 3.75, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 50/25 Kabel Upsell Mission", code: "5BV:US3", value: 6.25, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 100/50 Kabel Upsell Mission", code: "4BV:US3", value: 7.50, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 250/50 Kabel Upsell Mission", code: "3BV:US3", value: 8.75, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 500/50 Kabel Upsell Mission", code: "2BV:US3", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 1000/50 Kabel Upsell Mission", code: "1BV:US3", value: 13.75, class: "VKD_KIP_VVL" },
  { prod: "GZ CableMax 1000", code: "8BV:na", value: 0.00, class: "VKD_KIP_VVL" },

  // Prevention (KIP)
  { prod: "GigaZuhause I&P 50/25 Kabel Prevention Promo", code: "05H:K24", value: 15.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause I&P 100/50 Kabel Prevention Mission", code: "04H:KV2", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause I&P 250/50 Kabel Prevention Mission", code: "03H:KV2", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause I&P 250/50 Kabel Prevention Mission (High)", code: "03H:KV3", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause I&P 250/50 Kabel Prevention Mission (Std)", code: "03H:KVG", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause I&P 500/50 Kabel Prevention Mission", code: "02H:KV2", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause I&P 500/50 Kabel Prevention Mission (Std)", code: "02H:KVG", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause I&P 1000/50 Kabel Prevention Mission", code: "01H:KV2", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause I&P 1000/50 Kabel Prevention Mission (Std)", code: "01H:KVG", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 50/25 Kabel Prevention Mission", code: "5BV:KVG", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 100/50 Kabel Prevention Mission", code: "4BV:KV2", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 100/50 Kabel Prevention Mission (High)", code: "4BV:KV3", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 250/50 Kabel Prevention Mission", code: "3BV:KVG", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 250/50 Kabel Prevention Mission (High)", code: "3BV:KV3", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 500/50 Kabel Prevention Mission", code: "2BV:KV2", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 1000/50 Kabel Prevention Mission", code: "1BV:KVG", value: 10.00, class: "VKD_KIP_VVL" },
  
  // Prevention Promo (12 Monate reduziert)
  { prod: "GigaZuhause BV 50/25 Kabel Prevention Promo 12x9,99", code: "5BV:K12", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 100/50 Kabel Prevention Promo 12x19,99", code: "4BV:K12", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 250/50 Kabel Prevention Promo 12x19,99", code: "3BV:K12", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 500/50 Kabel Prevention Promo 12x19,99", code: "2BV:K12", value: 10.00, class: "VKD_KIP_VVL" },
  { prod: "GigaZuhause BV 1000/50 Kabel Prevention Promo 12x19,99", code: "1BV:K12", value: 10.00, class: "VKD_KIP_VVL" },

  // Business Internet (VVL)
  { prod: "Red Internet Business 100/50 Cable", code: "15C:na", value: 4.50, class: "VKD_KIP_VVL" },
  { prod: "Red Internet Business 300/50 Cable", code: "23C:na", value: 4.50, class: "VKD_KIP_VVL" },
  { prod: "Red Internet Business 500 Cable", code: "02C:na", value: 7.20, class: "VKD_KIP_VVL" },
  { prod: "Red Internet Business 1000 Cable", code: "01C:na", value: 7.20, class: "VKD_KIP_VVL" },
  { prod: "Red Business Internet 100/50 Cable Standard", code: "35C:na", value: 4.50, class: "VKD_KIP_VVL" },
  { prod: "Red Business Internet 300/50 Cable Standard", code: "33C:na", value: 4.50, class: "VKD_KIP_VVL" },
  { prod: "Red Business Internet 500/50 Cable Standard", code: "32C:na", value: 7.20, class: "VKD_KIP_VVL" },
  { prod: "Red Business Internet 1000/50 Cable Standard", code: "31C:na", value: 7.20, class: "VKD_KIP_VVL" },
  { prod: "Red Internet & Phone Business 100/50 Cable", code: "15B:na", value: 4.50, class: "VKD_KIP_VVL" },
  { prod: "Red Internet & Phone Business 300/50 Cable", code: "13B:na", value: 4.50, class: "VKD_KIP_VVL" },
  { prod: "Red Internet & Phone Business 500 Cable", code: "02B:na", value: 7.20, class: "VKD_KIP_VVL" },
  { prod: "Red Internet & Phone Business 1000 Cable", code: "01B:na", value: 7.20, class: "VKD_KIP_VVL" },
  { prod: "Red Business Internet & Phone 100/50 Cable", code: "35B:na", value: 4.50, class: "VKD_KIP_VVL" },
  { prod: "Red Business Internet & Phone 300/50 Cable", code: "33B:na", value: 4.50, class: "VKD_KIP_VVL" },
  { prod: "Red Business Internet & Phone 500/50 Cable", code: "32B:na", value: 7.20, class: "VKD_KIP_VVL" },
  { prod: "Red Business Internet & Phone 1000/50 Cable", code: "31B:na", value: 7.20, class: "VKD_KIP_VVL" },

  // ==========================================
  // INTERNET / KIP - BNT (Neukunden)
  // ==========================================
  { prod: "Red Phone 12M Standard", code: "PC2:na", value: 7.20, class: "VKD_KIP_BNT" },
  { prod: "Red Phone 12M Neukunde", code: "PC2:12T", value: 7.20, class: "VKD_KIP_BNT" },
  { prod: "GigaZuhause BV 50/25 Kabel 12M", code: "6BV:12T", value: 2.00, class: "VKD_KIP_BNT" },
  { prod: "GigaZuhause BV 50/25 Kabel Promo", code: "5BV:N09", value: 21.25, class: "VKD_KIP_BNT" },
  { prod: "GigaZuhause BV 100/50 Kabel Promo", code: "4BV:B09", value: 26.25, class: "VKD_KIP_BNT" },
  { prod: "GigaZuhause BV 250/50 Kabel Promo", code: "3BV:B09", value: 32.50, class: "VKD_KIP_BNT" },
  { prod: "GigaZuhause BV 500/50 Kabel Promo", code: "2BV:B09", value: 32.50, class: "VKD_KIP_BNT" },
  { prod: "GigaZuhause BV 1000/50 Kabel Promo", code: "1BV:B09", value: 45.00, class: "VKD_KIP_BNT" },
  { prod: "GigaZuhause BV CableMax 1000 NK", code: "9BV:24M", value: 50.00, class: "VKD_KIP_BNT" },
  { prod: "GigaZuhause 1000 Kabel VUM", code: "RGEP1:I", value: 45.00, class: "VUM_KIP_BNT" },

  // Business Internet (BNT)
  { prod: "Red Business Internet 100/50 Cable 6M Promo", code: "35C:N06", value: 19.00, class: "VKD_KIP_BNT" },
  { prod: "Red Business Internet 300/50 Cable 12M Promo", code: "33C:N12", value: 20.00, class: "VKD_KIP_BNT" },
  { prod: "Red Business Internet 500/50 Cable 12M Promo", code: "32C:N12", value: 22.50, class: "VKD_KIP_BNT" },
  { prod: "Red Business Internet 1000/50 Cable 12M Promo", code: "31C:N12", value: 27.50, class: "VKD_KIP_BNT" },
  { prod: "Red Business Internet & Phone 100/50 Cable 6M Promo", code: "35B:N06", value: 19.00, class: "VKD_KIP_BNT" },
  { prod: "Red Business Internet & Phone 300/50 Cable 12M Promo", code: "33B:N12", value: 25.00, class: "VKD_KIP_BNT" },
  { prod: "Red Business Internet & Phone 500/50 Cable 12M Promo", code: "32B:N12", value: 30.00, class: "VKD_KIP_BNT" },
  { prod: "Red Business Internet & Phone 1000/50 Cable 12M Promo", code: "31B:N12", value: 33.75, class: "VKD_KIP_BNT" },

  // ==========================================
  // ENV / CONNECT / WOHNUNGSWIRTSCHAFT
  // ==========================================
  { prod: "TV Connect", code: "SAB:24M", value: 19.00, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect Start VV Markt", code: "KV9:na", value: 19.20, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect Start VV Coop", code: "KVC:na", value: 19.20, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect Start VV Sonderpreis", code: "KVS:na", value: 19.20, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect Start BV Coop", code: "KBC:na", value: 19.20, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect Start BV Markt", code: "KB9:na", value: 19.20, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect Start BV Sonderpreis", code: "KBS:na", value: 19.20, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect", code: "TC2:na", value: 19.20, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect 12M", code: "TC2:12M", value: 5.00, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect 12M Tarifwechsel", code: "TC2:TW2", value: 5.00, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect Standard", code: "TCM:na", value: 19.20, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect Standard Tarifwechsel", code: "TCM:TW1", value: 7.50, class: "VKD_ENV_BNT" },
  { prod: "Vodafone TV Connect Zuhause BV 24M", code: "TCZ:na", value: 19.20, class: "VKD_ENV_BNT" },

  // ==========================================
  // MOBILE - VVL (Vertragsverlängerung)
  // ==========================================
  { prod: "Black", code: "BLACK19UL", value: 20.00, class: "MOB_VVL" },
  // Vodafone Smart XS Variants
  { prod: "Vodafone Smart XS", code: "SM2XSOS", value: 5.00, class: "MOB_VVL" },
  { prod: "Vodafone Smart XS", code: "SM2XSH05", value: 5.00, class: "MOB_VVL" },
  // GigaMobil XS Variants
  { prod: "GigaMobil XS", code: "GM2XSOS", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil XS", code: "GM2XSH05", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil XS", code: "GM2XSH10", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil XS", code: "GM2XSH20", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil XS", code: "GM2XSH30", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil XS", code: "GM2F12XS", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil XS", code: "GM2F24XS", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil XS", code: "GM2F36XS", value: 5.00, class: "MOB_VVL" },
  // GigaMobil S Variants
  { prod: "GigaMobil S", code: "GM2SOS", value: 6.30, class: "MOB_VVL" },
  { prod: "GigaMobil S", code: "GM2SH05", value: 6.30, class: "MOB_VVL" },
  { prod: "GigaMobil S", code: "GM2SH10", value: 6.30, class: "MOB_VVL" },
  { prod: "GigaMobil S", code: "GM2SH20", value: 6.30, class: "MOB_VVL" },
  { prod: "GigaMobil S", code: "GM2SH30", value: 6.30, class: "MOB_VVL" },
  { prod: "GigaMobil S", code: "GM112SOS", value: 6.30, class: "MOB_VVL" },
  { prod: "GigaMobil S", code: "GM2F12S", value: 6.30, class: "MOB_VVL" },
  { prod: "GigaMobil S", code: "GM2F24S", value: 6.30, class: "MOB_VVL" },
  { prod: "GigaMobil S", code: "GM2F36S", value: 6.30, class: "MOB_VVL" },
  // GigaMobil M Variants
  { prod: "GigaMobil M", code: "GM2MOS", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil M", code: "GM2MH05", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil M", code: "GM2MH10", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil M", code: "GM2MH20", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil M", code: "GM2MH30", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil M", code: "GM2MH40", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil M", code: "GM1MH40", value: 12.00, class: "MOB_VVL" }, // Extra entry from end of list
  { prod: "GigaMobil M", code: "GM2F12M", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil M", code: "GM2F24M", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil M", code: "GM2F36M", value: 12.00, class: "MOB_VVL" },
  // GigaMobil L Variants
  { prod: "GigaMobil L", code: "GM2LOS", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil L", code: "GM2LH05", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil L", code: "GM2LH10", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil L", code: "GM2LH20", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil L", code: "GM2LH30", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil L", code: "GM2LH40", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil L", code: "GM2F12L", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil L", code: "GM2F36L", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil L", code: "GM2F24L", value: 13.50, class: "MOB_VVL" },
  // GigaMobil XL Variants
  { prod: "GigaMobil XL", code: "GM2ULOS", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil XL", code: "GM2ULH05", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil XL", code: "GM2ULH10", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil XL", code: "GM2ULH20", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil XL", code: "GM2ULH30", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil XL", code: "GM2ULH40", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil XL", code: "GM2F12UL", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil XL", code: "GM2F24UL", value: 13.50, class: "MOB_VVL" },
  { prod: "GigaMobil XL", code: "GM2F36UL", value: 13.50, class: "MOB_VVL" },
  // GigaMobil Young XS Variants
  { prod: "GigaMobil Young XS", code: "GMY2XSOS", value: 4.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XS", code: "GMY2XSH05", value: 4.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XS", code: "GMY2XSH10", value: 4.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XS", code: "GMY2XSH20", value: 4.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XS", code: "GMY2XSH30", value: 4.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XS", code: "GY2F12XS", value: 4.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XS", code: "GY2F24XS", value: 4.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XS", code: "GY2F36XS", value: 4.00, class: "MOB_VVL" },
  // GigaMobil Young S Variants
  { prod: "GigaMobil Young S", code: "GMY2SOS", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young S", code: "GMY2SH05", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young S", code: "GMY2SH10", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young S", code: "GMY2SH20", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young S", code: "GMY2SH30", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young S", code: "GMY2SH40", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young S", code: "GY2F12S", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young S", code: "GY2F24S", value: 5.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young S", code: "GY2F36S", value: 5.00, class: "MOB_VVL" },
  // GigaMobil Young M Variants
  { prod: "GigaMobil Young M", code: "GMY2MOS", value: 8.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young M", code: "GMY2MH05", value: 8.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young M", code: "GMY2MH10", value: 8.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young M", code: "GMY2MH20", value: 8.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young M", code: "GMY2MH30", value: 8.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young M", code: "GMY2MH40", value: 8.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young M", code: "GY2F12M", value: 8.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young M", code: "GY2F24M", value: 8.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young M", code: "GY2F36M", value: 8.00, class: "MOB_VVL" },
  // GigaMobil Young L Variants
  { prod: "GigaMobil Young L", code: "GMY2LOS", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young L", code: "GMY2LH05", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young L", code: "GMY2LH10", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young L", code: "GMY2LH20", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young L", code: "GMY2LH30", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young L", code: "GMY2LH40", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young L", code: "GY2F12L", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young L", code: "GY2F24L", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young L", code: "GY2F36L", value: 12.00, class: "MOB_VVL" },
  // GigaMobil Young XL Variants
  { prod: "GigaMobil Young XL", code: "GMY2ULOS", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XL", code: "GMY2ULH05", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XL", code: "GMY2ULH10", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XL", code: "GMY2ULH20", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XL", code: "GMY2ULH30", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XL", code: "GMY2ULH40", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XL", code: "GY2F12UL", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XL", code: "GY2F24UL", value: 12.00, class: "MOB_VVL" },
  { prod: "GigaMobil Young XL", code: "GY2F36UL", value: 12.00, class: "MOB_VVL" },
  // Red + Data / FamilyCard VVL
  { prod: "VF Red + Data", code: "REPL2DOS", value: 1.00, class: "MOB_VVL" },
  { prod: "VF Red + Data", code: "REPL2D10", value: 1.00, class: "MOB_VVL" },
  { prod: "VF Red + Data", code: "REPL2D20", value: 1.00, class: "MOB_VVL" },
  { prod: "FamilyCard S", code: "GM1FSOS", value: 5.00, class: "MOB_VVL" },
  { prod: "FamilyCard S", code: "GM1FSH05", value: 5.00, class: "MOB_VVL" },
  { prod: "FamilyCard S", code: "GM1FSH10", value: 5.00, class: "MOB_VVL" },
  { prod: "FamilyCard S", code: "GM1FSH20", value: 5.00, class: "MOB_VVL" },
  { prod: "FamilyCard S", code: "GM1FSH30", value: 5.00, class: "MOB_VVL" },
  { prod: "FamilyCard M", code: "GM1FMOS", value: 7.50, class: "MOB_VVL" },
  { prod: "FamilyCard M", code: "GM1FMH05", value: 7.50, class: "MOB_VVL" },
  { prod: "FamilyCard M", code: "GM1FMH10", value: 7.50, class: "MOB_VVL" },
  { prod: "FamilyCard M", code: "GM1FMH20", value: 7.50, class: "MOB_VVL" },
  { prod: "FamilyCard M", code: "GM1FMH30", value: 7.50, class: "MOB_VVL" },
  { prod: "FamilyCard L", code: "GM1FLOS", value: 10.00, class: "MOB_VVL" },
  { prod: "FamilyCard L", code: "GM1FLH05", value: 10.00, class: "MOB_VVL" },
  { prod: "FamilyCard L", code: "GM1FLH10", value: 10.00, class: "MOB_VVL" },
  { prod: "FamilyCard L", code: "GM1FLH20", value: 10.00, class: "MOB_VVL" },
  { prod: "FamilyCard L", code: "GM1FLH30", value: 10.00, class: "MOB_VVL" },
  { prod: "FamilyCard L", code: "GM1FLH40", value: 10.00, class: "MOB_VVL" },
  { prod: "FamilyCard XL", code: "GM1FXLOS", value: 12.00, class: "MOB_VVL" },
  { prod: "FamilyCard XL", code: "GM1FXLH05", value: 12.00, class: "MOB_VVL" },
  { prod: "FamilyCard XL", code: "GM1FXLH10", value: 12.00, class: "MOB_VVL" },
  { prod: "FamilyCard XL", code: "GM1FXLH20", value: 12.00, class: "MOB_VVL" },
  { prod: "FamilyCard XL", code: "GM1FXLH30", value: 12.00, class: "MOB_VVL" },
  { prod: "FamilyCard XL", code: "GM1FXLH40", value: 12.00, class: "MOB_VVL" },
  // DataGo VVL
  { prod: "DataGo S", code: "MBBV_SOS", value: 5.00, class: "MOB_VVL" },
  { prod: "DataGo S", code: "MBBV_S5", value: 5.00, class: "MOB_VVL" },
  { prod: "DataGo S", code: "MBBV_S10", value: 5.00, class: "MOB_VVL" },
  { prod: "DataGo M", code: "MBBV_MOS", value: 5.00, class: "MOB_VVL" },
  { prod: "DataGo M", code: "MBBV_M5", value: 5.00, class: "MOB_VVL" },
  { prod: "DataGo M", code: "MBBV_M10", value: 5.00, class: "MOB_VVL" },
  { prod: "DataGo L", code: "MBBV_LOS", value: 5.00, class: "MOB_VVL" },
  { prod: "DataGo L", code: "MBBV_L5", value: 5.00, class: "MOB_VVL" },
  { prod: "DataGo L", code: "MBBV_L10", value: 5.00, class: "MOB_VVL" },
  { prod: "DataGo XL", code: "MBBV_XLOS", value: 5.00, class: "MOB_VVL" },
  { prod: "DataGo XL", code: "MBBV_XL5", value: 5.00, class: "MOB_VVL" },
  { prod: "DataGo XL", code: "MBBV_XL10", value: 5.00, class: "MOB_VVL" },
  // GigaCube VVL
  { prod: "GigaCube ZH Flex 2025", code: "GC25WP", value: 1.00, class: "MOB_VVL" },
  { prod: "GigaCube ZH Flex o. Router 2025", code: "GC25WPOS", value: 1.00, class: "MOB_VVL" },
  { prod: "GigaCube ZH 100 o. Router 2025", code: "GC25100OS", value: 8.10, class: "MOB_VVL" },
  { prod: "GigaCube ZH 100 4G-Router 2025", code: "GC25100", value: 8.10, class: "MOB_VVL" },
  { prod: "GigaCube ZH 100 5G-Router 2025", code: "GC2510010", value: 8.10, class: "MOB_VVL" },
  { prod: "GigaCube ZH 200 o. Router 2025", code: "GC25200OS", value: 8.10, class: "MOB_VVL" },
  { prod: "GigaCube ZH 200 4G-Router 2025", code: "GC25200", value: 8.10, class: "MOB_VVL" },
  { prod: "GigaCube ZH 200 5G-Router 2025", code: "GC2520010", value: 8.10, class: "MOB_VVL" },
  { prod: "GigaCube ZH Unl. o. Router 2025", code: "GC25ULOS", value: 8.10, class: "MOB_VVL" },
  { prod: "GigaCube ZH Unl. 4G-Router 2025", code: "GC25UL", value: 8.10, class: "MOB_VVL" },
  { prod: "GigaCube ZH Unl. 5G-Router 2025", code: "GC25UL10", value: 8.10, class: "MOB_VVL" },
  { prod: "GigaCube ZH Unl. 12M o. Router", code: "12GC25UOS", value: 1.80, class: "MOB_VVL" },
  { prod: "GigaCube ZH Unl. 12M 4G-Router", code: "12GC25UL", value: 1.80, class: "MOB_VVL" },
  { prod: "GigaCube ZH Unl. 12M 5G-Router", code: "12GC25U10", value: 1.80, class: "MOB_VVL" },
  { prod: "GigaCube ZH Unl.", code: "GC22UL", value: 22.50, class: "MOB_VVL" },
  // Talk24
  { prod: "Talk24", code: "VFZH24FFN", value: 1.80, class: "MOB_VVL" },
  { prod: "Talk24", code: "VF_ZH24FF", value: 1.80, class: "MOB_VVL" },

  // ==========================================
  // MOBILE - BNT (Neukunden)
  // ==========================================
  { prod: "Black", code: "BLACK19UL", value: 92.50, class: "MOB_BNT" },
  { prod: "Vodafone Smart XS", code: "SM2XSOS", value: 8.00, class: "MOB_BNT" },
  { prod: "Vodafone Smart XS", code: "SM2XSH05", value: 8.00, class: "MOB_BNT" },
  // GigaMobil XS BNT
  { prod: "GigaMobil XS", code: "GM2XSOS", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil XS", code: "GM2XSH05", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil XS", code: "GM2XSH10", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil XS", code: "GM2XSH20", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil XS", code: "GM2XSH30", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil XS", code: "GM2F12XS", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil XS", code: "GM2F24XS", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil XS", code: "GM2F36XS", value: 27.50, class: "MOB_BNT" },
  // GigaMobil S BNT
  { prod: "GigaMobil S", code: "GM2SOS", value: 40.00, class: "MOB_BNT" },
  { prod: "GigaMobil S", code: "GM2SH05", value: 40.00, class: "MOB_BNT" },
  { prod: "GigaMobil S", code: "GM2SH10", value: 40.00, class: "MOB_BNT" },
  { prod: "GigaMobil S", code: "GM2SH20", value: 40.00, class: "MOB_BNT" },
  { prod: "GigaMobil S", code: "GM2SH30", value: 40.00, class: "MOB_BNT" },
  { prod: "GigaMobil S", code: "GM112SOS", value: 40.00, class: "MOB_BNT" },
  { prod: "GigaMobil S", code: "GM2F12S", value: 40.00, class: "MOB_BNT" },
  { prod: "GigaMobil S", code: "GM2F24S", value: 40.00, class: "MOB_BNT" },
  { prod: "GigaMobil S", code: "GM2F36S", value: 40.00, class: "MOB_BNT" },
  // GigaMobil M BNT
  { prod: "GigaMobil M", code: "GM2MOS", value: 45.00, class: "MOB_BNT" },
  { prod: "GigaMobil M", code: "GM2MH05", value: 45.00, class: "MOB_BNT" },
  { prod: "GigaMobil M", code: "GM2MH10", value: 45.00, class: "MOB_BNT" },
  { prod: "GigaMobil M", code: "GM2MH20", value: 45.00, class: "MOB_BNT" },
  { prod: "GigaMobil M", code: "GM2MH30", value: 45.00, class: "MOB_BNT" },
  { prod: "GigaMobil M", code: "GM2MH40", value: 45.00, class: "MOB_BNT" },
  { prod: "GigaMobil M", code: "GM2F12M", value: 45.00, class: "MOB_BNT" },
  { prod: "GigaMobil M", code: "GM2F24M", value: 45.00, class: "MOB_BNT" },
  { prod: "GigaMobil M", code: "GM2F36M", value: 45.00, class: "MOB_BNT" },
  // GigaMobil L BNT
  { prod: "GigaMobil L", code: "GM2LOS", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil L", code: "GM2LH05", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil L", code: "GM2LH10", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil L", code: "GM2LH20", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil L", code: "GM2LH30", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil L", code: "GM2LH40", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil L", code: "GM2F12L", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil L", code: "GM2F36L", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil L", code: "GM2F24L", value: 50.00, class: "MOB_BNT" },
  // GigaMobil XL BNT
  { prod: "GigaMobil XL", code: "GM2ULOS", value: 55.00, class: "MOB_BNT" },
  { prod: "GigaMobil XL", code: "GM2ULH05", value: 55.00, class: "MOB_BNT" },
  { prod: "GigaMobil XL", code: "GM2ULH10", value: 55.00, class: "MOB_BNT" },
  { prod: "GigaMobil XL", code: "GM2ULH20", value: 55.00, class: "MOB_BNT" },
  { prod: "GigaMobil XL", code: "GM2ULH30", value: 55.00, class: "MOB_BNT" },
  { prod: "GigaMobil XL", code: "GM2ULH40", value: 55.00, class: "MOB_BNT" },
  { prod: "GigaMobil XL", code: "GM2F12UL", value: 55.00, class: "MOB_BNT" },
  { prod: "GigaMobil XL", code: "GM2F24UL", value: 55.00, class: "MOB_BNT" },
  { prod: "GigaMobil XL", code: "GM2F36UL", value: 55.00, class: "MOB_BNT" },
  // Young XS BNT
  { prod: "GigaMobil Young XS", code: "GMY2XSOS", value: 18.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young XS", code: "GMY2XSH05", value: 18.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young XS", code: "GMY2XSH10", value: 18.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young XS", code: "GMY2XSH20", value: 18.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young XS", code: "GMY2XSH30", value: 18.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young XS", code: "GY2F12XS", value: 18.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young XS", code: "GY2F24XS", value: 18.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young XS", code: "GY2F36XS", value: 18.00, class: "MOB_BNT" },
  // Young S BNT
  { prod: "GigaMobil Young S", code: "GMY2SOS", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young S", code: "GMY2SH05", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young S", code: "GMY2SH10", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young S", code: "GMY2SH20", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young S", code: "GMY2SH30", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young S", code: "GMY2SH40", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young S", code: "GY2F12S", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young S", code: "GY2F24S", value: 27.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young S", code: "GY2F36S", value: 27.50, class: "MOB_BNT" },
  // Young M BNT
  { prod: "GigaMobil Young M", code: "GMY2MOS", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young M", code: "GMY2MH05", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young M", code: "GMY2MH10", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young M", code: "GMY2MH20", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young M", code: "GMY2MH30", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young M", code: "GMY2MH40", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young M", code: "GY2F12M", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young M", code: "GY2F24M", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young M", code: "GY2F36M", value: 50.00, class: "MOB_BNT" },
  // Young L BNT
  { prod: "GigaMobil Young L", code: "GMY2LOS", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young L", code: "GMY2LH05", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young L", code: "GMY2LH10", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young L", code: "GMY2LH20", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young L", code: "GMY2LH30", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young L", code: "GMY2LH40", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young L", code: "GY2F12L", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young L", code: "GY2F24L", value: 50.00, class: "MOB_BNT" },
  { prod: "GigaMobil Young L", code: "GY2F36L", value: 50.00, class: "MOB_BNT" },
  // Young XL BNT
  { prod: "GigaMobil Young XL", code: "GMY2ULOS", value: 52.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young XL", code: "GMY2ULH05", value: 52.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young XL", code: "GMY2ULH10", value: 52.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young XL", code: "GMY2ULH20", value: 52.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young XL", code: "GMY2ULH30", value: 52.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young XL", code: "GMY2ULH40", value: 52.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young XL", code: "GY2F12UL", value: 52.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young XL", code: "GY2F24UL", value: 52.50, class: "MOB_BNT" },
  { prod: "GigaMobil Young XL", code: "GY2F36UL", value: 52.50, class: "MOB_BNT" },
  // Red + Data / FamilyCard BNT
  { prod: "VF Red + Data", code: "REPL2DOS", value: 7.20, class: "MOB_BNT" },
  { prod: "VF Red + Data", code: "REPL2D10", value: 7.20, class: "MOB_BNT" },
  { prod: "VF Red + Data", code: "REPL2D20", value: 7.20, class: "MOB_BNT" },
  { prod: "FamilyCard S", code: "GM1FSOS", value: 13.75, class: "MOB_BNT" },
  { prod: "FamilyCard S", code: "GM1FSH05", value: 13.75, class: "MOB_BNT" },
  { prod: "FamilyCard S", code: "GM1FSH10", value: 13.75, class: "MOB_BNT" },
  { prod: "FamilyCard S", code: "GM1FSH20", value: 13.75, class: "MOB_BNT" },
  { prod: "FamilyCard S", code: "GM1FSH30", value: 13.75, class: "MOB_BNT" },
  { prod: "FamilyCard M", code: "GM1FMOS", value: 20.00, class: "MOB_BNT" },
  { prod: "FamilyCard M", code: "GM1FMH05", value: 20.00, class: "MOB_BNT" },
  { prod: "FamilyCard M", code: "GM1FMH10", value: 20.00, class: "MOB_BNT" },
  { prod: "FamilyCard M", code: "GM1FMH20", value: 20.00, class: "MOB_BNT" },
  { prod: "FamilyCard M", code: "GM1FMH30", value: 20.00, class: "MOB_BNT" },
  { prod: "FamilyCard L", code: "GM1FLOS", value: 35.00, class: "MOB_BNT" },
  { prod: "FamilyCard L", code: "GM1FLH05", value: 35.00, class: "MOB_BNT" },
  { prod: "FamilyCard L", code: "GM1FLH10", value: 35.00, class: "MOB_BNT" },
  { prod: "FamilyCard L", code: "GM1FLH20", value: 35.00, class: "MOB_BNT" },
  { prod: "FamilyCard L", code: "GM1FLH30", value: 35.00, class: "MOB_BNT" },
  { prod: "FamilyCard L", code: "GM1FLH40", value: 35.00, class: "MOB_BNT" },
  { prod: "FamilyCard XL", code: "GM1FXLOS", value: 39.00, class: "MOB_BNT" },
  { prod: "FamilyCard XL", code: "GM1FXLH05", value: 39.00, class: "MOB_BNT" },
  { prod: "FamilyCard XL", code: "GM1FXLH10", value: 39.00, class: "MOB_BNT" },
  { prod: "FamilyCard XL", code: "GM1FXLH20", value: 39.00, class: "MOB_BNT" },
  { prod: "FamilyCard XL", code: "GM1FXLH30", value: 39.00, class: "MOB_BNT" },
  { prod: "FamilyCard XL", code: "GM1FXLH40", value: 39.00, class: "MOB_BNT" },
  // DataGo BNT
  { prod: "DataGo M", code: "MBBV_MOS", value: 20.00, class: "MOB_BNT" },
  { prod: "DataGo M", code: "MBBV_M5", value: 20.00, class: "MOB_BNT" },
  { prod: "DataGo M", code: "MBBV_M10", value: 20.00, class: "MOB_BNT" },
  // GigaCube BNT
  { prod: "GigaCube ZH Flex 2025", code: "GC25WP", value: 14.40, class: "MOB_BNT" },
  { prod: "GigaCube ZH Flex o. Router 2025", code: "GC25WPOS", value: 14.40, class: "MOB_BNT" },
  { prod: "GigaCube ZH 100 o. Router 2025", code: "GC25100OS", value: 22.50, class: "MOB_BNT" },
  { prod: "GigaCube ZH 100 4G-Router 2025", code: "GC25100", value: 22.50, class: "MOB_BNT" },
  { prod: "GigaCube ZH 100 5G-Router 2025", code: "GC2510010", value: 22.50, class: "MOB_BNT" },
  { prod: "GigaCube ZH 200 o. Router 2025", code: "GC25200OS", value: 31.25, class: "MOB_BNT" },
  { prod: "GigaCube ZH 200 4G-Router 2025", code: "GC25200", value: 31.25, class: "MOB_BNT" },
  { prod: "GigaCube ZH 200 5G-Router 2025", code: "GC2520010", value: 31.25, class: "MOB_BNT" },
  { prod: "GigaCube ZH Unl. o. Router 2025", code: "GC25ULOS", value: 22.50, class: "MOB_BNT" },
  { prod: "GigaCube ZH Unl. 4G-Router 2025", code: "GC25UL", value: 22.50, class: "MOB_BNT" },
  { prod: "GigaCube ZH Unl. 5G-Router 2025", code: "GC25UL10", value: 22.50, class: "MOB_BNT" },
  { prod: "GigaCube ZH Unl. 12M o. Router", code: "12GC25UOS", value: 22.50, class: "MOB_BNT" },
  { prod: "GigaCube ZH Unl. 12M 4G-Router", code: "12GC25UL", value: 22.50, class: "MOB_BNT" },
  { prod: "GigaCube ZH Unl. 12M 5G-Router", code: "12GC25U10", value: 22.50, class: "MOB_BNT" },
  // Smart Tech / IoT
  { prod: "Smart Tech OneNumber inkl. Basic Device", code: "CIOT2FH10", value: 10.00, class: "MOB_BNT" },
  { prod: "Smart Tech OneNumber inkl. Device", code: "CIOT2FH15", value: 10.00, class: "MOB_BNT" },
  { prod: "Smart Tech OneNumber inkl. Premium Device", code: "CIOT2FH20", value: 10.00, class: "MOB_BNT" },
  { prod: "Smart Tech OneNumber inkl. Premium Device Plus", code: "CIOT2FH25", value: 10.00, class: "MOB_BNT" },
  { prod: "Smart Tech M", code: "CIOT2MOS", value: 10.00, class: "MOB_BNT" },
  { prod: "Smart Tech M", code: "CIOT2MH4", value: 10.00, class: "MOB_BNT" },
  { prod: "Smart Tech M", code: "CIOT2MH9", value: 10.00, class: "MOB_BNT" },

  // ==========================================
  // OPTIONS & HARDWARE (Option)
  // ==========================================
  { prod: "Ultra Hub 7 Kabel", code: "PHA:na", value: 0.80, class: "Option" },
  { prod: "Option Homebox6 (Fritz!Box 6690)", code: "OHC:na", value: 0.80, class: "Option" },
  { prod: "Option Homebox5 (Fritz!Box 6660)", code: "OHE:na", value: 0.80, class: "Option" },
  { prod: "WLAN-HOTSPOT Business 32 Promo", code: "0H0:B10", value: 6.75, class: "Option" },
  { prod: "WLAN-HOTSPOT Business Premium 32 Promo", code: "0H1:B20", value: 6.75, class: "Option" },
  { prod: "Option Homebox6 (Fritz!Box 6690) WIN", code: "OHC:B24", value: 0.80, class: "Option" },
  { prod: "Option Homebox Fritz!Box 6690 WIN", code: "OHI:B24", value: 0.80, class: "Option" },
  { prod: "Option Homebox Fritz!Box 6670", code: "OHJ:na", value: 0.80, class: "Option" },
  { prod: "Option Homebox Fritz!Box 6690", code: "OHK:na", value: 0.80, class: "Option" },
  { prod: "SuperWLAN 7 Verstärker 1 1M", code: "PSW:na", value: 0.80, class: "Option" },
  { prod: "SuperWLAN 7 Verstärker 2 1M", code: "1ZE:na", value: 0.80, class: "Option" },
  { prod: "SuperWLAN 7 Verstärker 3 1M", code: "2ZE:na", value: 0.80, class: "Option" },
  { prod: "SuperWLAN 7 Verstärker 4 1M", code: "3ZE:na", value: 0.80, class: "Option" },
  { prod: "SuperWLAN 7 Verstärker 5 1M", code: "VZE:na", value: 0.80, class: "Option" },
  { prod: "SuperWLAN Verstärker MVLZ 6M", code: "SWI:na", value: 0.80, class: "Option" },
  { prod: "SuperWLAN Verstärker 1 MVLZ 1M", code: "ZE1:na", value: 0.80, class: "Option" },
  { prod: "SuperWLAN Verstärker 2 MVLZ 1M", code: "ZE2:na", value: 0.80, class: "Option" },
  { prod: "SuperWLAN Verstärker 3 MVLZ 1M", code: "ZE3:na", value: 0.80, class: "Option" },
  { prod: "SuperWLAN Verstärker 4 MVLZ 1M", code: "ZE4:na", value: 0.80, class: "Option" },

  // ==========================================
  // VERSICHERUNGEN (MOB_BNT)
  // ==========================================
  { prod: "Handyversicherung", code: "24HATAV23", value: 7.00, class: "MOB_BNT" },
  { prod: "Vodafone Cover Plus (mit Diebstahlschutz) 5,99", code: "CO5SD1060", value: 7.00, class: "MOB_BNT" },
  { prod: "Vodafone Cover Plus (mit Diebstahlschutz) 7,99", code: "CO5SD1080", value: 7.00, class: "MOB_BNT" },
  { prod: "Vodafone Cover Plus (mit Diebstahlschutz) 9,99", code: "CO5SD1100", value: 7.00, class: "MOB_BNT" },
  { prod: "Vodafone Cover Plus (mit Diebstahlschutz) 11,99", code: "CO5SD1120", value: 7.00, class: "MOB_BNT" },
  { prod: "Vodafone Cover Plus (mit Diebstahlschutz) 13,99", code: "CO5SD1140", value: 7.00, class: "MOB_BNT" },
  { prod: "Vodafone Cover (ohne Diebstahlschutz) 2,99", code: "CB5SD1030", value: 7.00, class: "MOB_BNT" },
  { prod: "Vodafone Cover (ohne Diebstahlschutz) 4,99", code: "CB5SD1050", value: 7.00, class: "MOB_BNT" },
  { prod: "Vodafone Cover (ohne Diebstahlschutz) 6,99", code: "CB5SD1070", value: 7.00, class: "MOB_BNT" },
  { prod: "Vodafone Cover (ohne Diebstahlschutz) 8,99", code: "CB5SD1090", value: 7.00, class: "MOB_BNT" },
  { prod: "Vodafone Cover (ohne Diebstahlschutz) 10,99", code: "CB5SD1110", value: 7.00, class: "MOB_BNT" },

  // ==========================================
  // NEXT BEST ACTION (NBA)
  // ==========================================
  { prod: "Low NBA - Tipp 1", code: "Mobile NBA", value: 18.00, class: "NBA" },
  { prod: "High NBA - Tipp 2", code: "Mobile NBA", value: 18.00, class: "NBA" },
  { prod: "Downsell NBA*", code: "Mobile NBA", value: 18.00, class: "NBA" },
  { prod: "NBA Tipp Cable", code: "Kabel NBA", value: 10.00, class: "NBA" },

  // ==========================================
  // DSL (KLARTEXT)
  // ==========================================
  { prod: "DSL 100", code: "GigaZuhause 100 DSL", value: 10.00, class: "DSL_VVL" },
  { prod: "DSL 50", code: "GigaZuhause 50 DSL", value: 10.00, class: "DSL_VVL" },
  { prod: "DSL 250", code: "PK Internet-Flat GZH 250 DSL 10/25", value: 10.00, class: "DSL_BNT" }
];

export const PIX_CONFIG = {
    BNT: [0, 2.79, 2.99, 3.19, 3.39, 3.59, 3.79, 3.99, 4.19, 4.49, 4.80, 5.10, 5.40, 5.70, 6.00, 6.30, 6.60, 6.90, 7.19, 999],
    BNT_P:[0, 1.0,  1.5,  2.0,  2.5,  3.0,  3.5,  4.0,  4.5,  5.0,  5.5,  6.0,  6.5,  7.0,  7.5,  8.0,  8.5,  9.0,  9.5, 10.0],
    VVL: [0, 1.79, 2.09, 2.39, 2.69, 2.99, 3.29, 3.59, 3.89, 4.19, 4.49, 4.80, 5.10, 5.40, 5.70, 6.00, 6.30, 6.60, 6.90, 999],
    VVL_P:[0, 1.0,  1.5,  2.0,  2.5,  3.0,  3.5,  4.0,  4.5,  5.0,  5.5,  6.0,  6.5,  7.0,  7.5,  8.0,  8.5,  9.0,  9.5, 10.0]
};

export const COACHING_TIPS = [
    { id: 'cs', th: 90, title: 'CS Kritisch (<90%)', text: 'Kunde fühlt sich nicht gehört.', tools: 'ERA-Modell, Verbales Nicken, 3 Calls hören' },
    { id: 'ff7', th: 75, title: 'FF7 Problem (<75%)', text: 'Fachwissen oder Doku fehlt.', tools: 'AskVodafone Guide, W-Fragen' },
    { id: 'storno', th: 20, title: 'Storno Hoch (>20%)', text: 'Jubelperser? Laufzeit verschwiegen?', tools: 'Transparenz-Check, Verint' }
];
